// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version for this example

package main

import (
	"context"
	"google.golang.org/grpc"
)

// Protobuf message types
type ProtoSchool struct {
	Id                string
	RegistrationNumber string
	Name              string
	Address           string
	Phone             string
	Email             string
	CreatedAt         string
	UpdatedAt         string
}

type GetSchoolRequest struct {
	Id string
}

type GetSchoolResponse struct {
	School *ProtoSchool
	Found  bool
}

type ValidateSchoolRequest struct {
	Id string
}

type ValidateSchoolResponse struct {
	Exists bool
	Name   string
}

// gRPC service interface
type SchoolServiceServer interface {
	GetSchool(context.Context, *GetSchoolRequest) (*GetSchoolResponse, error)
	ValidateSchool(context.Context, *ValidateSchoolRequest) (*ValidateSchoolResponse, error)
}

// Register function (simplified)
func RegisterSchoolServiceServer(s *grpc.Server, srv SchoolServiceServer) {
	// In a real implementation, this would register the service with gRPC
}
